spring:
  application:
    name: jbooking

  datasource:
    url: jdbc:postgresql://localhost:5435/jbooking
    username: ${DB_USERNAME:sparrow}
    password: ${DB_PASSWORD:9376570167}
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true
        format_sql: true

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:public}

server:
  port: ${SERVER_PORT:8081}
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json, text/plain
